name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

defaults:
  run:
    shell: cmd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - name: telemetry off
      shell: cmd
      run: echo "::set-env name=DOTNET_CLI_TELEMETRY_OPTOUT::true"

    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - uses: nuget/setup-nuget@v1
    - run: nuget restore ForTheKingSaveEdit.sln -NonInteractive
    - run: msbuild -restore -property:Configuration=Release -maxCPUCount ForTheKingSaveEdit.sln
    - uses: actions/upload-artifact@v2
      with:
        name: for-the-king-save-editor-${{ github.sha }}.zip
        path: ForTheKingSaveEdit/bin/x64/Release
